version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:
            - npm install -g sonarqube-scanner
            - cd devawsfrontend
            - npm install
    build:
        commands:
            - npm run coverage
    post_build:
        commands:
            - npm run sonar